config/routes.rb
Fuel::Application.routes.draw do
  get "home/index"

  devise_for :users

  scope "api" do
    resources :cars, :tankings, :stations
  end
  
  match '/stadistics' => 'home#stadistics', :as => :stadistics

  root :to => "home#index"

end

app/models/tanking.rb
class Tanking < ActiveRecord::Base
	validates :user_id, :presence => true
	validates :car_id, :presence => true
	validates :station_id, :presence => true
	validates :money, :presence => true
	validates :gal, :presence => true
	validates :km, :presence => true

	belongs_to :user
	belongs_to :car
	belongs_to :station
end

app/controllers/tankings_controller.rb
class TankingsController < ApplicationController
	before_filter :authenticate_user!

	before_filter :get, :only => [:edit, :update, :destroy]
	before_filter :add_user, :only => [:create, :update]
	before_filter :new_station, :only => [:create, :update]
	before_filter :validate_user, :only => [:edit, :update, :destroy]

	def get
		@tanking = Tanking.find(params[:id], :conditions => ["user_id = ?", current_user.id])
	end

	def add_user
		params[:tanking][:user_id]= current_user.id
	end

	def validate_user
		if(@tanking.user_id != current_user.id)
			redirect_to(@tanking, :notice => "You can't modify this tanking")
		end
	end

	def new_station
		if(params[:tanking][:name].length > 0)
			@station = Station.find_or_create_by_name_and_user_id(params[:tanking][:name], current_user.id)
			params[:tanking][:station_id] = @station.id
		end
	end

	def index
		@tankings = Tanking.select('"tankings"."id", station_id, car_id, name, mark, model, year, date, money, gal, km').joins(:car, :station).where("tankings.user_id = #{current_user.id} AND car_id = #{params[:car_id]}").order("date DESC")

		respond_to do |format|
	      format.html # index.html.erb
	      format.json { render json: @tankings }
	    end
	end

	def new
		@tanking = Tanking.new
	end

	def edit
	end

	def update
		params[:tanking].delete :name
		params[:tanking].delete :mark
		params[:tanking].delete :model
		params[:tanking].delete :year
		
	    respond_to do |format|
	      if @tanking.update_attributes(params[:tanking])
	        format.html { redirect_to(tankings_url, :notice => 'Tanking was successfully updated.') }
	        format.json  { render :json => @tanking, :status => :created, :location => @tanking }
	      else
	        format.html { render :action => "new" }
	        format.json  { render :json => @tanking.errors, :status => :unprocessable_entity }
	      end
	    end
	end

	def create
		params[:tanking].delete :name
		@tanking = Tanking.new(params[:tanking])
	    respond_to do |format|
	      if @tanking.save
	        format.html { redirect_to(tankings_url, :notice => 'Tanking was successfully created.') }
	        format.json  { render :json => @tanking, :status => :created, :location => @tanking }
	      else
	        format.html { render :action => "new" }
	        format.json  { render :json => @tanking.errors, :status => :unprocessable_entity }
	      end
	    end
	end

	def destroy
		@tanking.destroy

		respond_to do |format|
			format.html { redirect_to(tankings_url, :notice => 'Tanking was successfully deleted.') }
			format.json  { head :ok }
		end
	end
end

app/helpers/tankings_helper.rb
module TankingsHelper
end

app/views/tankings/_form.html.erb
<%= form_for(@tanking, :html => {:class => "form-horizontal"}) do |f| %>
	<fieldset>
	<legend></legend>

	<div class="control-group">
		<%= f.label :car, :class => "control-label" %>
		<div class="controls"><%= f.collection_select :car_id, Car.where(:user_id => current_user.id), :id, :name_car, {:include_blank => 'Select One'} %></div>
	</div>

	<div class="control-group">
		<%= f.label :station, :class => "control-label" %>
		<div class="controls"><%= f.collection_select :station_id, Station.where(:user_id => current_user.id), :id, :name, {:include_blank => '-New Station-'} %></div>
	</div>

	<div class="control-group">
		<div class="control-label"><label for="station_name">¿New Station?</label></div>
		<div class="controls"><input class="input-xlarge" id="station_name" name="station_name"type="text"></div>
	</div>

	<div class="control-group">
		<%= f.label :money, :class => "control-label" %>
		<div class="controls"><%= f.text_field :money, :class => "input-xlarge" %></div>
	</div>

	<div class="control-group">
		<%= f.label :gal, :class => "control-label" %>
		<div class="controls"><%= f.text_field :gal, :class => "input-xlarge" %></div>
	</div>

	<div class="control-group">
		<%= f.label :km, :class => "control-label" %>
		<div class="controls"><%= f.text_field :km, :class => "input-xlarge" %></div>
	</div>

	<div class="control-group">
		<%= f.label :date, :class => "control-label" %>
		<div class="controls"><%= f.date_select :date %></div>
	</div>

	<% if @tanking.errors.any? %>
		<div class="alert alert-block" id="alert">
			<a class="close" data-dismiss="alert">x</a>
			<h4 class="alert-heading">Warning!</h4>
			Please check the following <%= pluralize(@tanking.errors.count, "message") %>:
			<ul>
				<% @tanking.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-actions">
		<%= f.submit :class => "btn btn-primary" %>
		<%= link_to "Cancel", tankings_path, :class => "btn" %>
	</div>
	</fieldset>
<% end %>

app/views/tankings/edit.html.erb
<h2>Edit Tanking</h2>

<%= render "form" %>

app/views/tankings/index.html.erb
<h2>My Tankings</h2>

<% if(@tankings.count > 0) %>
	<table class="table table-bordered">
		<tr>
			<th>Edit</th>
			<th>Delete</th>
			<th>Date</th>
			<th>Car</th>
			<th>Station</th>
			<th>Money</th>
			<th>Gals</th>
			<th>Km</th>
		</tr>
		<% @tankings.each do |tanking| %>
		<tr>
			<td><%= link_to "Edit", edit_tanking_path(tanking.id), :class => "btn btn-warning" %></td>
			<td><%= link_to "Delete", tanking, :method => "delete", :confirm => "¿Are you sure?", :class => "btn btn-danger" %></td>
			<td><%= tanking.date %></td>
			<td><%= "#{tanking.mark} - #{tanking.model} (#{tanking.year})" %></td>
			<td><%= tanking.name %></td>
			<td>$ <%= tanking.money %></td>
			<td><%= tanking.gal %></td>
			<td><%= tanking.km %></td>
		</tr>
		<% end %>
	</table>
<% else %>
	<div class="alert alert-info">
		There is no tankings registed yet.
	</div>
<% end %>
<%= link_to "New Tanking", new_tanking_path, :class => "btn" %>

app/views/tankings/new.html.erb
<h2>New Tanking</h2>

<%= render "form" %>