config/routes.rb
Fuel::Application.routes.draw do
  get "home/index"

  devise_for :users

  scope "api" do
    resources :cars, :tankings, :stations
  end
  
  match '/stadistics' => 'home#stadistics', :as => :stadistics

  root :to => "home#index"

end

app/models/car.rb
class Car < ActiveRecord::Base
	validates :user_id, :presence => true
	validates :mark, :presence => true
	validates :model, :presence => true
	validates :year, :presence => true

	belongs_to :user

	def name_car
		"#{self.mark} - #{self.model} (#{self.year})"
	end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@cars = Car.where("user_id= ?", current_user.id)

		respond_to do |format|
	      format.html # index.html.erb
	      format.json { render json: @cars }
	    end
	end

	def show
		@car = Car.find(params[:id])
		@data = Hash.new
		all_records = Tanking.where(:user_id => current_user.id, :car_id => @car.id).order("date")
		all_records.each do |row|
		  if(!@data.has_key?(row.date))
		    @data[row.date] = { :date  =>  row.date, :cars => {} }
		  end
		  #if(@data.has_key?(row.date))
		  if(!@data[row.date][:cars].has_key?(row.car_id))
		    @data[row.date][:cars][row.car_id] = {:id => row.car_id, :gal => row.gal }
		  else
		    @data[row.date][:cars][row.car_id][:gal] = @data[row.date][:cars][row.car_id][:gal].to_i + row.gal.to_i
		  end
		end
	end

	def edit
		@car = Car.find(params[:id])
	end

	def create
		params[:car][:user_id] = current_user.id
		@car = Car.new(params[:car])

	    respond_to do |format|
	      if @car.save
	        format.html { redirect_to(cars_url, :notice => 'Car was successfully created.') }
	        format.json  { render :json => @car, :status => :created, :location => @car }
	      else
	        format.html { render :action => "new" }
	        format.json  { render :json => @car.errors, :status => :unprocessable_entity }
	      end
	    end
	end

	def update
		@car = Car.find(params[:id])
		respond_to do |format|
	      if @car.update_attributes(params[:car])
	        format.html { redirect_to(cars_url, :notice => 'Car was successfully updated.') }
	        format.json  { head :no_content }
	      else
	        format.html { render :action => "edit" }
	        format.json  { render :json => @car.errors, :status => :unprocessable_entity }
	      end
		end
	end

	# TODO: we have to delete all tankings of this car
	def destroy
		@car = Car.find(params[:id])
		@car.destroy

		respond_to do |format|
			format.html { redirect_to cars_url }
			format.json { head :no_content }
	end
	end	
end

app/helpers/car_helper.rb
module CarHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car, :html => {:class => "form-horizontal"}) do |f| %>
  <fieldset>
  <legend></legend>

  <div class="control-group">
    <%= f.label :mark, :class => "control-label" %>
    <div class="controls"><%= f.text_field :mark, :class => "input-xlarge" %></div>
  </div>

  <div class="control-group">
    <%= f.label :model, :class => "control-label" %>
    <div class="controls"><%= f.text_field :model, :class => "input-xlarge" %></div>
  </div>

  <div class="control-group">
    <%= f.label :year, :class => "control-label" %>
    <div class="controls"><%= f.text_field :year, :class => "input-xlarge" %></div>
  </div>

  <div class="control-group">
    <%= f.label :color, :class => "control-label" %>
    <div class="controls"><%= f.text_field :color, :class => "input-xlarge" %></div>
  </div>

  <% if @car.errors.any? %>
    <div class="alert alert-block" id="alert">
      <a class="close" data-dismiss="alert">x</a>
      <h4 class="alert-heading">Warning!</h4>
      Please check the following <%= pluralize(@car.errors.count, "message") %>:
      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <% end %>

  <div class="form-actions">
    <%= f.submit :class => "btn btn-primary" %>
    <%= link_to "Cancel", cars_path, :class => "btn" %>
  </div>
  </fieldset>
<% end %>

app/views/cars/edit.html.erb
<h2>Edit Car</h2>

<%= render "form" %>

app/views/cars/index.html.erb
<h2>My cars</h2>

<% if(@cars.count > 0) %>
	<table class="table table-bordered">
		<tr>
			<th>Show</th>
			<th>Edit</th>
			<th>Mark</th>
			<th>Model</th>
			<th>Year</th>
			<th>Color</th>
		</tr>
		<% @cars.each do |car| %>
		<tr>
			<td><%= link_to "View", car, :class => "btn btn-info" %></td>
			<td><%= link_to "Edit", edit_car_path(car), :class => "btn btn-warning" %></td>
			<td><%= car.mark %></td>
			<td><%= car.model %></td>
			<td><%= car.year %></td>
			<td><%= car.color %></td>
		</tr>
		<% end %>
	</table>
<% else %>
	<div class="alert alert-info">
		There is no cars registed yet.
	</div>
<% end %>
<%= link_to "New Car", new_car_path, :class => "btn" %>

app/views/cars/new.html.erb
<h2>New Car</h2>

<%= render "form" %>

app/views/cars/show.html.erb
<h2>Car: <%= @car.mark+" - "+@car.model %></h2>

<table border="0" cellpadding="8">
	<tr>
		<td>Mark</td>
		<td>:</td>
		<td><%= @car.mark %></td>
	</tr>
	<tr>
		<td>Model</td>
		<td>:</td>
		<td><%= @car.model %></td>
	</tr>
	<tr>
		<td>Year</td>
		<td>:</td>
		<td><%= @car.year %></td>
	</tr>
	<tr>
		<td>Color</td>
		<td>:</td>
		<td><%= @car.color %></td>
	</tr>
</table>
<%= link_to "Edit", edit_car_path(@car), :class => "btn btn-warning" %>
<%= link_to "Back", cars_path, :class => "btn" %>

<script type="text/javascript">
	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Year');
		data.addColumn('number', '<%= @car.mark+" - "+@car.model+" ("+@car.year+")" %>');
		data.addRows([<% 
			sw = false
			@data.each do |day| %><%= 
				if(sw)
					p ","
				end
				%>
				['<%= day[1][:date] %>', <%
							gal = day[1][:cars][@car.id][:gal] %><%= 
							p gal %><%
		  		 %>]<% 
		  		sw = true
		  	end %>
		]);

		var options = {
		  interpolateNulls: true,
		  vAxis: { title: "Gallons" },
		  hAxis: { title: "Tankings" }
		};

		var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
		chart.draw(data, options);
	}
</script>
<br><br><h3>Gas consuption</h3>
<div id="chart_div" style="width: 800px; height: 500px;"></div>